from __future__ import annotations

import escnn.group
from escnn.group import Group, GroupElement
from escnn.group import IrreducibleRepresentation, Representation
from escnn.group import utils

from .utils import *

import numpy as np
import math

from typing import Tuple, Callable, Iterable, List, Dict, Any


__all__ = ["MultiplicativeCyclicGroup"]


class MultiplicativeCyclicGroup(Group):

    PARAM = 'int'
    PARAMETRIZATIONS = [
        'int',          # integer in 0, 1, ..., N-1
        'scalar',       # scalar in b^(k-N//2), k=0,...,N-1
        # 'radians',      # real in 0., 2pi/N, ... i*2pi/N, ...
        # 'C',            # point in the unit circle (i.e. cos and sin of 'radians')
        # 'MAT',          # 2x2 rotation matrix
    ]

    def __init__(self, N: int, basis: float = 1.5):
        r"""
        Build an instance of a cyclic group of scalars :math:`C_N` containing :math:`N` discrete values.

        The group elements are 
        :math:`\{b^{- \lfloor N/2 \rfloor}, b^{- \lfloor N/2 \rfloor + 1}, \dots, b^0, \dots, b^{\lceil N/2 \rceil - 1}\}`, 
        where :math:`b` is the `basis`, with group law given by scalar multiplication:
        :math:`r^a \cdot r^b = r^{a+b}` (with exponents taken modulo the cyclic range).  
        The cyclic group :math:`C_N` is isomorphic to integers modulo :math:`N`, 
        and elements are stored as integers from :math:`0` to :math:`N-1` representing the corresponding powers of :math:`b`.

        Subgroup Structure.

        A subgroup of :math:`C_N` is another cyclic group :math:`C_M`, identified by the integer :math:`M` (the order of the subgroup).  
        If the current group is :math:`C_N`, the subgroup is generated by 
        :math:`r^{(N/M)}`. Note that :math:`M` must divide :math:`N`.

        Args:
            N (int): order of the group
            basis (float): geometric ratio defining the multiplicative steps between elements

        Attributes:
            ~.rotation_order (int): number of elements in the group
        """
        
        assert (isinstance(N, int) and N > 0), N
        assert isinstance(basis, float) and basis > 0, basis
        
        super().__init__("MC%d" % N, False, True)
        print('C3')
        self.N = N
        self.size = N
        self.basis = basis  # np.exp(2j * np.pi / N)

        # int: for consistency with the DihedralGroup, store the number of rotations also in this attribute
        # self.rotation_order = N # should keep it?

        #self._elements = [basis ** ((i % N) - (N // 2)) for i in range(N)]
        # self._elements = [MultiplicativeGroupElement(basis ** ((i % N) - (N // 2)), self) for i in range(N)]
        self._elements = [self.element(i) for i in range(N)]

        # self._identity = self._elements[N // 2] # correct here? Just set identity=1.0 ?
        self._identity = self._elements[N // 2]
        
        self._build_representations()

    @property
    def generators(self) -> List[GroupElement]:
        if self.order() > 1:
            return [self.element(1)]
        else:
            # the generator of the trivial group is the empty set
            return []

    @property
    def identity(self) -> GroupElement:
        return self._identity

    @property
    def elements(self) -> List[GroupElement]:
        return self._elements

    # @property
    # def elements_names(self) -> List[str]:
    #     return self._elements_names

    @property
    def _keys(self) -> Dict[str, Any]:
        return {'N': self.N, 'basis': self.basis}

    @property
    def subgroup_trivial_id(self):
        return 1

    @property
    def subgroup_self_id(self):
        return self.order()

    ###########################################################################
    # METHODS DEFINING THE GROUP LAW AND THE OPERATIONS ON THE GROUP'S ELEMENTS
    ###########################################################################

    def _inverse(self, element: int, param: str = PARAM) -> int:
        r"""
        Return the inverse element :math:`r^{-j \mod N}` of the input element :math:`r^j`, specified by the input
        integer :math:`j` (``element``)
        
        Args:
            element (int): a group element :math:`r^j`

        Returns:
            its opposite :math:`r^{-j \mod N}`
            
        """
        element = self._change_param(element, param, 'int')
        element = (-element) % self.N

        return self._change_param(element, 'int', param)

    def _combine(self, e1: int, e2: int, param: str = PARAM, param1: str = None, param2: str = None) -> int:
        r"""
        Return the composition of the two input elements.
        Given two integers :math:`a` and :math:`b` representing the elements :math:`r^a` and :math:`r^b`, the method
        returns the integer :math:`a + b \mod N` representing the element :math:`r^{a + b \mod N}`.
        

        Args:
            e1 (int): a group element :math:`r^a`
            e2 (int): another group element :math:`r^a`

        Returns:
            their composition :math:`r^{a+b \mod N}`
            
        """

        if param1 is None:
            param1 = param
        if param2 is None:
            param2 = param

        e1 = self._change_param(e1, p_from=param1, p_to='int')
        e2 = self._change_param(e2, p_from=param2, p_to='int')
        return self._change_param(
            (e1 + e2) % self.N,
            p_from = 'int',
            p_to = param
        )

    def _equal(self, e1: int, e2: int, param: str = PARAM, param1: str = None, param2: str = None) -> bool:
        r"""

        Check if the two input values corresponds to the same element.

        Args:
            e1 (int): an element
            e2 (int): another element

        Returns:
            whether they are the same element

        """
        if param1 is None:
            param1 = param
        if param2 is None:
            param2 = param

        e1 = self._change_param(e1, p_from=param1, p_to='int')
        e2 = self._change_param(e2, p_from=param2, p_to='int')
        return e1 == e2
    
    def _is_element(self, element: int, param: str = PARAM, verbose: bool = False) -> bool:
    
        element = self._change_param(element, p_from=param, p_to='int')
        if isinstance(element, int):
            return 0 <= element < self.N
        else:
            return False

    def _hash_element(self, element: int, param: str = PARAM):
        element = self._change_param(element, p_from=param, p_to='int')
        return hash(element)

    def _repr_element(self, element: int, param: str = PARAM):
        element = self._change_param(element, p_from=param, p_to='int')
        return f"{self.basis}**(({element}-({self.N}//2) % {self.N}))"
    
    def _change_param(self, element, p_from: str, p_to: str):
        # from integer to scalar
        if p_from == 'int' and p_to == 'scalar':
            half = self.N // 2
            return self.basis ** ((element % self.N) - half)
        # from scalar to integer
        elif p_from == 'scalar' and p_to == 'int':
            half = self.N // 2
            log_val = np.log(element) / np.log(self.basis)
            idx = int(round(log_val + half)) % self.N
            return idx
        # identity
        elif p_from == p_to:
            return element
        else:
            raise ValueError(f"Unsupported parameter conversion: {p_from} -> {p_to}")


    ###########################################################################

    def sample(self) -> GroupElement:
        return self.element(np.random.randint(0, self.order()))

    def testing_elements(self) -> Iterable[GroupElement]:
        r"""
        A finite number of group elements to use for testing.
        
        """
        return iter(self._elements)

    def __eq__(self, other):
        if not isinstance(other, MultiplicativeCyclicGroup):
            return False
        else:
            return self.name == other.name and self.order() == other.order()

    def _subgroup(self, id: int) -> Tuple[
        Group,
        Callable[[GroupElement], GroupElement],
        Callable[[GroupElement], GroupElement]
    ]:
        r"""
        Restrict the current group to the cyclic subgroup :math:`C_M`.
        If the current group is :math:`C_N`, it restricts to the subgroup generated by :math:`r^{(N/M)}`.
        Notice that :math:`M` has to divide the order :math:`N` of the current group.
        
        The method takes as input the integer :math:`M` identifying of the subgroup to build (the order of the subgroup)
        
        Args:
            id (int): the integer :math:`M` identifying of the subgroup

        Returns:
            a tuple containing

                - the subgroup,

                - a function which maps an element of the subgroup to its inclusion in the original group and

                - a function which maps an element of the original group to the corresponding element in the subgroup (returns None if the element is not contained in the subgroup)
                
        """

        assert isinstance(id, int), id

        order = id

        assert self.order() % order == 0, \
            "Error! The subgroups of a cyclic group have an order that divides the order of the supergroup." \
            " %d does not divide %d " % (order, self.order())

        # Build the subgroup
        
        # take the elements of the group generated by "r^ratio"
        sg = MultiplicativeCyclicGroup(order) # correct?

        # parent_mapping = lambda e, ratio=ratio: self.element(e._element * ratio)
        # child_mapping = lambda e, ratio=ratio, sg=sg: None if e._element % ratio != 0 else sg.element(int(e._element // ratio))
        parent_mapping = _build_parent_map(self, order)
        child_mapping = _build_child_map(self, sg)

        return sg, parent_mapping, child_mapping

    def grid(self, type: str, N: int) -> List[GroupElement]:
        r"""
            .. todo ::
                Add docs

        """

        if type == 'rand':
            return [self.sample() for _ in range(N)]
        elif type == 'regular':
            assert self.order() % N == 0
            r = self.order() // N
            return [self.element(i*r) for i in range(N)]
        else:
            raise ValueError(f'Grid type "{type}" not recognized!')

    def _combine_subgroups(self, sg_id1, sg_id2):
    
        sg_id1 = self._process_subgroup_id(sg_id1)
        sg1, inclusion, restriction = self.subgroup(sg_id1)
        sg_id2 = sg1._process_subgroup_id(sg_id2)
        
        return sg_id2

    def _restrict_irrep(self, irrep: Tuple, id: int) -> Tuple[np.matrix, List[Tuple]]:
        r"""
        
        Restrict the input irrep to the subgroup :math:`C_m` with order ``m``.
        If the current group is :math:`C_n`, it restricts to the subgroup generated by :math:`r^{(n/m)}`.
        Notice that :math:`m` has to divide the order :math:`n` of the current group.
        
        The method takes as input the integer :math:`m` identifying of the subgroup to build (the order of the subgroup)

        Args:
            irrep (tuple): the identifier of the irrep to restrict
            id (int): the integer ``m`` identifying the subgroup

        Returns:
            a pair containing the change of basis and the list of irreps of the subgroup which appear in the restricted irrep
            
        """
    
        irr = self.irrep(*irrep)

        sg, _, _ = self.subgroup(id)
        change_of_basis = np.eye(irr.size)

        f = irr.attributes["frequency"] % id
        r = (f,)
        irreps = [r]

        return change_of_basis, irreps

    def _build_representations(self):
        r"""
        Build the irreps and the regular representation for this group
        
        """
        
        N = self.order()

        # Build all the Irreducible Representations
        for k in range(0, N):
            self.irrep(k)
            
        # Build all Representations

        # add all the irreps to the set of representations already built for this group
        self.representations.update(**{irr.name : irr for irr in self.irreps()})
        print(self.representations)

        # build the regular representation
        self.representations['regular'] = self.regular_representation
        self.representations['regular'].supported_nonlinearities.add('vectorfield')
        
    def _build_quotient_representations(self):
        r"""
        Build all the quotient representations for this group

        """
        for n in range(2, int(math.ceil(math.sqrt(self.order())))):
            if self.order() % n == 0:
                self.quotient_representation(n)
    
    @property
    def trivial_representation(self) -> Representation:
        return self.representations['irrep_0']

    def irrep(self, k: int):
        id = (k,)

        if id not in self._irreps:

            assert 0 <= k < self.N, (k, self.N)
            name = f"irrep_{k}"

            irrep = _build_irrep_mul(k)
            character = _build_char_mul(k)

            supported_nonlinearities = ['pointwise', 'norm']

            self._irreps[id] = IrreducibleRepresentation(
                self,
                id,
                name,
                irrep,
                1,           # all irreps are 1D now
                'R',
                supported_nonlinearities=supported_nonlinearities,
                character=character,
                frequency=k
            )

        return self._irreps[id]


    def bl_irreps(self, L: int) -> List[Tuple]:
        r"""
        Returns a list containing the id of all irreps of frequency smaller or equal to ``L``.
        This method is useful to easily specify the irreps to be used to instantiate certain objects, e.g. the
        Fourier based non-linearity :class:`~escnn.nn.FourierPointwise`.
        """
        assert 0 <= L <= self.order(), (L, self.order())
        return [(l,) for l in range(L+1)]

    def _clebsh_gordan_coeff(self, m, n, j) -> np.ndarray:
        m, = self.get_irrep_id(m)
        n, = self.get_irrep_id(n)
        j, = self.get_irrep_id(j)

        rho_m = self.irrep(m)
        rho_n = self.irrep(n)
        rho_j = self.irrep(j)

        # In multiplicative group, all irreps are 1D
        if j == (m + n) % self.N:
            # 1x1 CG coefficient
            return np.ones((rho_m.size, rho_n.size, 1, rho_j.size))
        else:
            # no contribution
            return np.zeros((rho_m.size, rho_n.size, 0, rho_j.size))

    def _tensor_product_irreps(self, J: int, l: int) -> List[Tuple[Tuple, int]]:
        J, = self.get_irrep_id(J)
        l, = self.get_irrep_id(l)
    
        # In the multiplicative group all irreps are 1D and combine by addition mod N
        j = (J + l) % self.N

        return [
            ((j,), 1)
        ]

    _cached_group_instances = {}
    
    @classmethod
    def _generator(cls, N: int) -> 'MultiplicativeCyclicGroup':
        if N not in cls._cached_group_instances:
            cls._cached_group_instances[N] = MultiplicativeCyclicGroup(N)
        
        return cls._cached_group_instances[N]


def _build_irrep_mul(k: int):
    def irrep(element: GroupElement, k: int = k):
        exp = element.to('int') - element.group.size // 2
        value = element.group.basis ** exp
        return np.array([[value ** k]])
    return irrep

def _build_char_mul(k: int):
    def character(element: GroupElement, k=k):
        exp = element.to('int') - element.group.size // 2
        value = element.group.basis ** exp
        return value ** k
    return character


def _build_parent_map(G: MultiplicativeCyclicGroup, order: int):
    def parent_mapping(e: GroupElement, G: Group = G, order=order) -> GroupElement:
        return G.element(e.to('int') * G.order() // order)
    
    return parent_mapping


def _build_child_map(G: MultiplicativeCyclicGroup, sg: MultiplicativeCyclicGroup):
    assert G.order() % sg.order() == 0
    
    def child_mapping(e: GroupElement, G=G, sg: Group = sg) -> GroupElement:
        assert e.group == G
        i = e.to('int')
        ratio = G.order() // sg.order()
        if i % ratio != 0:
            return None
        else:
            return sg.element(i // ratio)
    
    return child_mapping

class MultiplicativeGroupElement(GroupElement):
    def __init__(self, value: float, group):
        super().__init__(value, group)
        self.value = value

    def __matmul__(self, other):
        return MultiplicativeGroupElement(self.value * other.value, self.group)

    # def __matmul__(self, other):
    #     product = self.value * other.value
    #     # find the corresponding element in the group's element list
    #     for e in self.group._elements:
    #         if abs(e.value - product) < 1e-12:
    #             return e
    #     raise ValueError("Resulting element not found in group")

    # def __repr__(self):
    #     return f"{self.value}"
    
    # def to(self, param='int'):
    #     if param == 'int':
    #         # map value to integer index in the cyclic group
    #         return self.group._elements.index(self.value)
    #     elif param == 'float':
    #         return self.value
    #     else:
    #         raise ValueError(param)


